### ISSUE TITLE
Add a template for this trigger

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin-trigger-command#20]
It would be super useful to have a template for this trigger, to streamline DX

**Comment by calebschoepp** [comment]
@me-diru this could also be an interesting thing for you to work on in the coming weeks.

**Comment by me-diru** [comment]
Thanks for sharing! I will explore how to add templates. I am not sure what "this trigger" is in this context.

**Comment by calebschoepp** [comment]
"this trigger" is implying the `spin-trigger-command`. `spin-trigger-command` is a custom trigger for Spin that runs some code right on startup. We're looking for a template that we'll scaffold out a project around this trigger similar to [this](https://developer.fermyon.com/hub/preview/template_http_rust).

**Comment by ThorstenHans** [comment]
#26 will add the `command-rust` template. IMO, it would be nice to have templates for other popular languages as well 😄

**Comment by radu-matei** [comment]
Added a Rust template in #26.
@karthik2804 suggested he would like to add a JavaScript template as well.
