### ISSUE TITLE
outbound-hosts restriction is not honored when running this trigger

### ISSUE THREAD

**Issue by rajatjindal** [fermyon/spin-trigger-command#33]
try changing the url in the`async` example without changing the allowed outbound hosts. and observe that it can still make an outgoing request even when that new url is not safelisted in spin.toml

I verified this is not an issue with a regular trigger-http.

**Comment by radu-matei** [comment]
I can reproduce this as well and when `allowed_outbound_hosts` is empty or missing.

```toml
allowed_outbound_hosts = []
```
